name: Build and Deploy WebGL

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: $UNITY_LICENSE
        with:
          targetPlatform: WebGL
      - uses: actions/upload-artifact@v3
        with:
          name: Build
          path: build/WebGL
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/download-artifact@v3
        with:
          name: Build
          path: docs/Build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: docs
          github_token: ${{ secrets.GITHUB_TOKEN }}
